EXECUTABLES = fft6

#CC=g++ -std=c++11
CC=g++-4.4

all: $(EXECUTABLES)

COMMON_INC = ../common
VPATH = ../common

fft6: EventStats.cpp utils.cpp clSetup.cpp kernel.cpp fft6.cpp
	$(CC) -O3 -g -w -I$(COMMON_INC) $(CL_CFLAGS) $(CL_LDFLAGS) -o$@ $^ -lm -lrt -fopenmp -lOpenCL
clean:
	rm -f $(EXECUTABLES) *.o
